spring:
  application:
    name: best-process
  datasource:
    url: jdbc:tc:postgresql:11:///test

server:
  port: 8080
  servlet:
    context-path: /${spring.application.name}
  error:
    include-stacktrace: always
    nclude-message: always

logging:
  level:
    root: info